---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)


data("nyc_airbnb")

nyc_airbnb = nyc_airbnb |> 
  mutate(stars = review_scores_location/2) |> 
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type, lat, long)
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_vec = nyc_airbnb |> pull(borough) |> unique()

selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"),
  choices = borough_vec,
  selected = "Manhattan"
)

sliderInput(
  inputId= "price_range",
  label = h3("Select a price range"),
  min = 50, max = 1000,
  value = c(100,400)
)



##storing something called input and in the background storing lists that we've defined. this created an option for users to define input
##you can alter the size of headers with h3
## you can also define a character vector so that you don't have to manually define inputs
##we created a dropdown menu and a slider

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
##renderText({input[["borough_choice"]]})

renderPlotly({nyc_airbnb |> 
  filter(
    borough== input[["borough_choice"]],
    price <input[["price_range"]][2],
    price>input[["price_range"]][1],
    room_type == "Entire home/apt"
  ) |> 
  plot_ly(x =~lat, y = ~long, type = "scatter", mode = "markers", color =~price)})

##you can wrap input choice into the render
##you can add a lot of inputs into one render
##input choice reacts based on what user does, so you can't just run it.
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}
renderText({input[["room_type"]]})
```

